export const PRESETS = [
  {
    id: "watermarks",
    label: "Watermark text",
    strings: [
      "This ebook was purchased by",
      "Licensed to:",
      "This copy is for personal use only",
      "For your personal reading only",
      "Do not share this file",
    ],
  },
  {
    id: "ads",
    label: "Advertisement text",
    strings: [
      "Visit us at",
      "More books available at",
      "Subscribe to our newsletter",
      "Join our mailing list",
      "Also by this author",
    ],
  },
  {
    id: "generator",
    label: "Generator tags",
    strings: [
      "Generated by",
      "Converted by",
      "calibre",
      "Sigil",
      "<meta name=\"generator\"",
    ],
  },
  {
    id: "oceanofpdf",
    label: "OceanofPDF watermark",
    strings: [
      "OceanofPDF.com",
    ],
  },
  {
    id: "drm-notices",
    label: "DRM/copyright notices",
    strings: [
      "This material is protected",
      "Unauthorized copying",
      "Digital Rights Management",
      "All rights reserved",
      "Distribution of this file is prohibited",
    ],
  },
];
